[package]
name = "noverplay-tui"
version = "1.0.0"
edition = "2024"
license = "GPL-3.0-only"
description = "Терминальный музыкальный клиент Noverplay"

[[bin]]
name = "noverplay"
path = "src/main.rs"

[[bin]]
name = "np"
path = "src/bin/np.rs"

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
cpal = "0.18"
crossbeam-channel = "0.5"
crossterm = { version = "0.29", features = ["event-stream"] }
directories = "6"
ed25519-dalek = { version = "2", features = ["rand_core"] }
futures-util = "0.3"
hex = "0.4"
keyring = "4"
rand_core = { version = "0.6", features = ["getrandom"] }
ratatui = "0.30"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "cookies", "json", "query", "rustls"] }
resvg = { version = "0.47", default-features = false }
rusqlite = { version = "0.37", default-features = false, features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
toml = "0.9"
symphonia = { version = "0.6", default-features = false, features = ["aac", "flac", "isomp4", "mkv", "mp3", "ogg", "pcm", "vorbis", "wav"] }
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
yandex-music = "0.4.8"
zeroize = "1"
global-hotkey = "0.7.0"
blowfish = "0.9"
cbc = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
md5 = "0.7"
aes = "0.8"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
