use crate::{
    account::{
        error::AccountApiError,
        models::{AccountAction, AccountSession, BootstrapUpdate, CaptchaChallenge},
    },
    app::Screen,
    audio::AudioEvent,
    model::TrackRef,
    onboarding::{
        SoundCloudAccess,
        zapret::{ZapretApplyResult, ZapretPlan},
    },
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Action {
    Quit,
    Navigate(Screen),
    Back,
    SelectPrevious,
    SelectNext,
    Activate,
    TogglePause,
    NextTrack,
    PreviousTrack,
    ChangeVolume(i8),
    Seek(i64),
    ToggleShuffle,
    CycleRepeat,
    ToggleLike,
    StartSearch,
    ToggleSearchFocus,
    FocusSearchInput,
    CycleSearchProvider,
    SearchInput(char),
    SearchBackspace,
    SubmitSearch,
    SearchFinished {
        query: String,
        tracks: Vec<TrackRef>,
        failures: Vec<String>,
    },
    ControlSearchFinished {
        tracks: Vec<TrackRef>,
        failures: Vec<String>,
    },
    WaveFinished {
        tracks: Vec<TrackRef>,
        failures: Vec<String>,
    },
    ControlWaveFinished {
        tracks: Vec<TrackRef>,
        failures: Vec<String>,
    },
    AudioProgress {
        position_ms: u64,
        buffered_ms: u64,
    },
    Audio(AudioEvent),
    PlaybackFailed(String),
    OpenHelp,
    OpenKeybindings,
    OpenCommandPalette,
    OpenPlaylistImport,
    OpenAccount(AccountAction),
    ToggleAccountMode,
    AccountLogout,
    MouseClick {
        column: u16,
        row: u16,
        terminal_width: u16,
        terminal_height: u16,
    },
    CloseModal,
    ModalSubmit,
    ModalPrevious,
    ModalNext,
    ModalToggle,
    ModalInput(char),
    ModalBackspace,
    CredentialSaved {
        kind: crate::credentials::CredentialKind,
        result: Result<(), String>,
    },
    PlaylistImported(Result<crate::model::Playlist, String>),
    LikeSaved {
        track: Box<TrackRef>,
        liked: bool,
        result: Result<(), String>,
    },
    AccountCaptchaLoaded {
        action: AccountAction,
        result: Result<CaptchaChallenge, AccountApiError>,
    },
    AccountAuthenticated(Result<AccountSession, AccountApiError>),
    AccountRestored(Result<Option<AccountSession>, AccountApiError>),
    BootstrapFinished(Result<BootstrapUpdate, AccountApiError>),
    AccountLoggedOut {
        result: Result<(), AccountApiError>,
        soundcloud_configured: bool,
    },
    SoundCloudChecked(SoundCloudAccess),
    ZapretPlanned(Result<Box<ZapretPlan>, String>),
    ZapretApplied(Result<ZapretApplyResult, String>),
    AudioOutputChanged(Result<String, String>),
    Tick,
    Resize,
}
