use crate::{
    app::Screen,
    audio::AudioEvent,
    model::TrackRef,
    onboarding::{
        SoundCloudAccess,
        zapret::{ZapretApplyResult, ZapretPlan},
    },
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Action {
    Quit,
    Navigate(Screen),
    SelectPrevious,
    SelectNext,
    Activate,
    TogglePause,
    NextTrack,
    PreviousTrack,
    ChangeVolume(i8),
    Seek(i64),
    ToggleShuffle,
    CycleRepeat,
    StartSearch,
    SearchInput(char),
    SearchBackspace,
    SubmitSearch,
    SearchFinished {
        query: String,
        tracks: Vec<TrackRef>,
        failures: Vec<String>,
    },
    WaveFinished {
        tracks: Vec<TrackRef>,
        failures: Vec<String>,
    },
    AudioProgress {
        position_ms: u64,
        buffered_ms: u64,
    },
    Audio(AudioEvent),
    PlaybackFailed(String),
    OpenHelp,
    OpenCommandPalette,
    CloseModal,
    ModalSubmit,
    ModalPrevious,
    ModalNext,
    ModalToggle,
    ModalInput(char),
    ModalBackspace,
    CredentialSaved {
        kind: crate::credentials::CredentialKind,
        result: Result<(), String>,
    },
    SoundCloudChecked(SoundCloudAccess),
    ZapretPlanned(Result<Box<ZapretPlan>, String>),
    ZapretApplied(Result<ZapretApplyResult, String>),
    AudioOutputChanged(Result<String, String>),
    Tick,
    Resize,
}
