pub mod account;
pub mod action;
pub mod app;
pub mod audio;
pub mod cli;
pub mod config;
pub mod credentials;
pub mod effect;
pub mod event;
pub mod importer;
pub mod model;
pub mod onboarding;
pub mod provider;
pub mod runtime;
pub mod secrets;
pub mod storage;
pub mod terminal;
pub mod ui;
pub mod wave;

pub const APP_NAME: &str = "Noverplay";
pub const APP_VERSION: &str = env!("CARGO_PKG_VERSION");
